"""
Cell Factory models for dynamic cell generation.

Models for AI-driven cell generation, including dynamic refs,
generation metadata, and sandbox execution state.
"""

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field

from .base import generate_uuid


class DynamicRef(BaseModel):
    """
    Reference to AI-generated asset in OPFS (Origin Private File System).

    Dynamic refs are ephemeral references to code assets generated by AI
    that are stored temporarily in OPFS before being promoted to persistent
    storage (MongoDB GridFS) upon cell promotion.
    """

    id: str = Field(
        default_factory=generate_uuid, description="Unique identifier for this ref"
    )
    type: Literal["logic", "style", "data", "component", "visual"] = Field(
        ...,
        description="Type of asset: logic (JS/Python), style (CSS), data (JSON), component (Vue), visual (SVG)",
    )
    lang: Literal["js", "css", "json", "vue", "svg", "python", "html"] = Field(
        ..., description="Programming language of the asset"
    )
    path: str = Field(
        ...,
        description="OPFS path to the asset (e.g., 'sandbox/assets/logic_abc123.js')",
    )
    filename: str = Field(..., description="Filename of the asset")
    size_bytes: int = Field(..., ge=0, description="Size of the asset in bytes")
    validated: bool = Field(
        default=False,
        description="Whether this ref has passed validation (syntax, security, rules)",
    )
    validation_errors: List[str] = Field(
        default_factory=list, description="List of validation errors if any"
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC timestamp when ref was created",
    )

    model_config = {"json_encoders": {datetime: lambda v: v.isoformat()}}


class GenerationMetadata(BaseModel):
    """
    Metadata about the AI generation process for a cell.

    Tracks the generation lifecycle, validation attempts, errors,
    and readiness for promotion to a typed cell.
    """

    prompt: str = Field(
        ..., description="Original user prompt that triggered generation"
    )
    model: str = Field(
        ..., description="AI model used for generation (e.g., 'gpt-4', 'claude-3')"
    )
    attempts: int = Field(
        default=1,
        ge=1,
        le=3,
        description="Number of generation attempts (Hypnosis Loop iterations)",
    )
    validation_errors: List[str] = Field(
        default_factory=list,
        description="Accumulated validation errors across all attempts",
    )
    auto_corrected: bool = Field(
        default=False,
        description="Whether the code was auto-corrected via Hypnosis Loop",
    )
    promotion_ready: bool = Field(
        default=False,
        description="Whether the cell is ready for promotion to typed cell",
    )
    generated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC timestamp when generation started",
    )
    completed_at: Optional[datetime] = Field(
        None,
        description="UTC timestamp when generation completed (successfully or failed)",
    )

    model_config = {"json_encoders": {datetime: lambda v: v.isoformat()}}


class SandboxExecutionState(BaseModel):
    """
    State of sandbox execution for a cell.

    Tracks the lifecycle of code execution within the isolated sandbox,
    including boot time, execution status, errors, and resource usage.
    """

    cell_id: str = Field(..., description="ID of the cell being executed")
    status: Literal[
        "booting", "running", "completed", "error", "timeout", "terminated"
    ] = Field(..., description="Current execution status")
    booted_at: Optional[datetime] = Field(
        None, description="UTC timestamp when sandbox was booted"
    )
    completed_at: Optional[datetime] = Field(
        None, description="UTC timestamp when execution completed"
    )
    execution_duration_ms: Optional[float] = Field(
        None, ge=0, description="Total execution duration in milliseconds"
    )
    error_message: Optional[str] = Field(
        None, description="Error message if execution failed"
    )
    console_output: List[str] = Field(
        default_factory=list, description="Console output from sandbox execution"
    )
    resource_usage: Optional[Dict[str, Any]] = Field(
        None, description="Resource usage statistics (memory, CPU time, etc.)"
    )

    model_config = {"json_encoders": {datetime: lambda v: v.isoformat()}}


class UnclassifiedCellData(BaseModel):
    """
    Extended data model for unclassified-cell with dynamic generation support.

    This model extends the base cell initial_data structure to support
    AI-driven code generation, storing dynamic refs and generation metadata
    before the cell is promoted to a typed cell.
    """

    title: str = Field(
        default="Nova Célula Sem Título",
        description="Human-readable title for the cell",
    )
    content: str = Field(
        default="", description="Markdown content or user prompt for generation"
    )
    category: str = Field(
        default="persistida", description="Cell category (ephemeral, persistida, etc.)"
    )
    icon: str = Field(default="📋", description="Emoji icon for the cell")

    # NEW: Dynamic generation fields
    dynamic_refs: List[DynamicRef] = Field(
        default_factory=list,
        description="List of dynamic refs to AI-generated assets in OPFS",
    )
    generation_metadata: Optional[GenerationMetadata] = Field(
        None, description="Metadata about the AI generation process"
    )
    sandbox_state: Optional[SandboxExecutionState] = Field(
        None, description="Current state of sandbox execution"
    )

    model_config = {"json_encoders": {datetime: lambda v: v.isoformat()}}


class CellPromotionRequest(BaseModel):
    """
    Request to promote an unclassified cell to a typed cell.

    Takes an unclassified cell with dynamic refs and creates a new
    cell type definition, persisting assets from OPFS to MongoDB GridFS.
    """

    cell_id: str = Field(..., description="ID of the unclassified cell to promote")
    new_type_name: str = Field(
        ...,
        min_length=3,
        max_length=100,
        description="Name for the new cell type (e.g., 'custom-chart-cell')",
    )
    new_type_description: Optional[str] = Field(
        None, description="Description of the new cell type"
    )
    category: str = Field(
        default="generated", description="Category for the new cell type"
    )


class CellPromotionResponse(BaseModel):
    """
    Response after successful cell promotion.
    """

    success: bool = Field(..., description="Whether promotion succeeded")
    new_cell_type_id: str = Field(..., description="ID of the newly created cell type")
    new_cell_id: str = Field(..., description="ID of the newly created cell instance")
    layout_book_synced: bool = Field(
        ..., description="Whether Layout Book was updated with new cell type"
    )
    persisted_assets_count: int = Field(
        ..., ge=0, description="Number of assets persisted to MongoDB GridFS"
    )
    message: str = Field(..., description="Success message")
    promoted_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC timestamp when promotion occurred",
    )

    model_config = {"json_encoders": {datetime: lambda v: v.isoformat()}}


class ConversationMessage(BaseModel):
    """
    A message in the conversation history.
    """

    role: Literal["user", "assistant", "system"] = Field(
        ..., description="Role of the message sender"
    )
    content: str = Field(..., description="Message content")
    timestamp: datetime = Field(
        default_factory=datetime.utcnow, description="When the message was created"
    )

    model_config = {"json_encoders": {datetime: lambda v: v.isoformat()}}


class RAGContext(BaseModel):
    """
    RAG (Retrieval-Augmented Generation) context for enriching prompts.
    """

    relevant_docs: List[str] = Field(
        default_factory=list, description="List of relevant document excerpts"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Additional metadata about retrieved context"
    )


class EnrichedPrompt(BaseModel):
    """
    Enriched prompt containing user input, conversation history, and RAG context.

    This is the core payload sent via Event Bus to the Wasm Orchestrator,
    containing all context needed for LLM generation without sensitive tokens.
    """

    user_prompt: str = Field(..., description="Original user prompt/request")
    conversation_history: List[ConversationMessage] = Field(
        default_factory=list, description="Previous messages in the conversation"
    )
    rag_context: Optional[RAGContext] = Field(
        None, description="RAG context if available"
    )
    system_instructions: Optional[str] = Field(
        None, description="System-level instructions for the LLM"
    )
    constraints: Dict[str, Any] = Field(
        default_factory=dict,
        description="Generation constraints (format, max_tokens, etc.)",
    )

    model_config = {"json_encoders": {datetime: lambda v: v.isoformat()}}


class CellGenerationRequest(BaseModel):
    """
    Request to generate code for a cell using AI.
    """

    cell_id: str = Field(..., description="ID of the cell to generate code for")
    content: str = Field(
        ..., min_length=10, description="User prompt/description for code generation"
    )
    format: Literal["svg", "vue", "js", "python", "auto"] = Field(
        default="auto", description="Desired output format (auto-detect if 'auto')"
    )
    model: str = Field(default="gpt-4", description="AI model to use for generation")
    conversation_id: Optional[str] = Field(
        None, description="ID of the conversation context to use"
    )
    use_rag: bool = Field(
        default=False, description="Whether to use RAG for context enrichment"
    )


class CellGenerationResponse(BaseModel):
    """
    Response after code generation request.
    """

    success: bool = Field(
        ..., description="Whether generation was initiated successfully"
    )
    cell_id: str = Field(..., description="ID of the cell being generated")
    stream_available: bool = Field(
        default=True, description="Whether streaming is available for this generation"
    )
    message: str = Field(..., description="Status message")


class ActionStep(BaseModel):
    """
    A single step in an action plan for recursive transmutation.

    Action steps can be atomic (executable directly) or composite
    (requiring further decomposition). Supports hierarchical task
    decomposition for complex cell generation workflows.
    """

    step_id: str = Field(
        default_factory=generate_uuid, description="Unique identifier for this step"
    )
    is_atomic: bool = Field(
        ...,
        description="Whether this step is atomic (directly executable) or needs decomposition",
    )
    action: str = Field(
        ...,
        description="Action type (e.g., 'generate_svg', 'create_component', 'fetch_data')",
    )
    tool: Optional[str] = Field(
        None,
        description="Tool/service to execute this step (e.g., 'llm_service', 'rag_service')",
    )
    parameters: Dict[str, Any] = Field(
        default_factory=dict, description="Parameters for executing this step"
    )
    description: str = Field(
        ..., description="Human-readable description of what this step accomplishes"
    )
    cell_type: Optional[str] = Field(
        None, description="Target cell type if this step generates a cell"
    )
    context_inheritance: Dict[str, Any] = Field(
        default_factory=dict,
        description="Context fragments inherited from parent step for nested decomposition",
    )
    substeps: List["ActionStep"] = Field(
        default_factory=list,
        description="Nested substeps for hierarchical decomposition",
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC timestamp when step was created",
    )

    model_config = {"json_encoders": {datetime: lambda v: v.isoformat()}}


class ActionPlan(BaseModel):
    """
    Structured action plan for recursive transmutation.

    Generated by the AI "Architect Mode" when task complexity exceeds
    threshold. Contains hierarchical steps for decomposing complex
    tasks into manageable atomic actions.
    """

    plan_id: str = Field(
        default_factory=generate_uuid,
        description="Unique identifier for this action plan",
    )
    original_cell_id: str = Field(
        ..., description="ID of the original cell that triggered plan generation"
    )
    original_prompt: str = Field(
        ..., description="Original user prompt that triggered this plan"
    )
    complexity_score: float = Field(
        ...,
        ge=0.0,
        le=10.0,
        description="Complexity score (0-10) that triggered decomposition",
    )
    steps: List[ActionStep] = Field(
        default_factory=list, description="Ordered list of action steps in the plan"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata (model used, generation time, etc.)",
    )
    status: Literal["pending", "executing", "completed", "failed"] = Field(
        default="pending", description="Current execution status of the plan"
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC timestamp when plan was created",
    )
    completed_at: Optional[datetime] = Field(
        None, description="UTC timestamp when plan execution completed"
    )

    model_config = {"json_encoders": {datetime: lambda v: v.isoformat()}}
