"""
Chunk Schema Models

Pydantic models for chunk data structures used in the ingestion pipeline.
Provides type safety and validation for chunks generated by chunking strategies
and consumed by the embeddings generation pipeline.

This module addresses the root cause identified in issue #1006, where lack of
schema validation led to field name mismatches causing runtime errors.
"""

from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field, field_validator, model_validator


class TargetCollection(str, Enum):
    """
    Target ChromaDB collection for embeddings.

    Collections:
        DOCS: scareverse_docs - Documentation and text content (Mistral embeddings)
        CODE: scareverse_code - Source code (DeepSeek-Coder embeddings)
        CONFIG: scareverse_config - Configuration files
    """

    DOCS = "scareverse_docs"
    CODE = "scareverse_code"
    CONFIG = "scareverse_config"


class ChunkType(str, Enum):
    """
    Type of chunk content.

    Types:
        MODULE_DOCSTRING: Python module-level docstring
        FUNCTION_DOCSTRING: Python function/method docstring
        CLASS_DOCSTRING: Python class docstring
        FULL_FILE: Complete file content
        UNPARSEABLE: Content that failed parsing
        MARKDOWN_SECTION: Markdown document section
        YAML_BLOCK: YAML configuration block
        JSON_BLOCK: JSON configuration block
        ENV_VAR: Environment variable definition
        VUE_TEMPLATE: Vue SFC template section
        VUE_SCRIPT: Vue SFC script section
        VUE_STYLE: Vue SFC style section
        JAVASCRIPT: JavaScript code chunk
        GENERIC_CODE: Generic code (other languages)
        GENERIC_DOC: Generic documentation
    """

    MODULE_DOCSTRING = "module_docstring"
    FUNCTION_DOCSTRING = "function_docstring"
    CLASS_DOCSTRING = "class_docstring"
    FULL_FILE = "full_file"
    UNPARSEABLE = "unparseable"
    MARKDOWN_SECTION = "markdown_section"
    YAML_BLOCK = "yaml_block"
    JSON_BLOCK = "json_block"
    ENV_VAR = "env_var"
    VUE_TEMPLATE = "vue_template"
    VUE_SCRIPT = "vue_script"
    VUE_STYLE = "vue_style"
    JAVASCRIPT = "javascript"
    GENERIC_CODE = "generic_code"
    GENERIC_DOC = "generic_doc"


class ChunkMetadata(BaseModel):
    """
    Metadata for a chunk.

    Attributes:
        chunk_id: Unique identifier for the chunk within a document
        document_id: Unique identifier for the source document
        source: Path to the source file
        file_type: Type of the source file (e.g., 'python', 'markdown')
        chunk_index: Sequential index of the chunk in the document
        chunk_type: Type of chunk content (optional)
        char_count: Number of characters in the chunk (optional)
        embedding_model_id: ID of the embedding model to use
        target_collection: Target ChromaDB collection

    Additional fields from specialized chunkers (e.g., markdown headers) are
    allowed via model_config.
    """

    model_config = {
        "extra": "allow",  # Allow additional fields from specialized chunkers
        "str_strip_whitespace": True,
    }

    chunk_id: str = Field(
        ...,
        description="Unique identifier for the chunk within a document",
        min_length=1,
    )
    document_id: str = Field(
        ..., description="Unique identifier for the source document", min_length=1
    )
    source: str = Field(..., description="Path to the source file", min_length=1)
    file_type: str = Field(
        ...,
        description="Type of the source file (e.g., 'python', 'markdown')",
        min_length=1,
    )
    chunk_index: int = Field(
        ..., ge=0, description="Sequential index of the chunk in the document"
    )
    chunk_type: Optional[str] = Field(None, description="Type of chunk content")
    char_count: Optional[int] = Field(
        None, ge=0, description="Number of characters in the chunk"
    )
    embedding_model_id: str = Field(
        ...,
        description="ID of the embedding model to use (e.g., 'mistral', 'deepseek-coder')",
        min_length=1,
    )
    target_collection: str = Field(..., description="Target ChromaDB collection")

    @field_validator("target_collection")
    @classmethod
    def validate_collection(cls, v: str) -> str:
        """
        Validate target collection is one of the known collections.

        Logs a warning if collection is unknown but allows it to support
        dynamic collection creation.
        """
        import logging

        valid_collections = {e.value for e in TargetCollection}
        if v not in valid_collections:
            logging.getLogger(__name__).warning(
                f"Unknown target collection '{v}'. Known collections: {valid_collections}"
            )
        return v

    @field_validator("embedding_model_id")
    @classmethod
    def validate_model_id(cls, v: str) -> str:
        """
        Validate embedding model ID is known.

        Logs a warning if model is unknown but allows it to support
        new models being added without code changes.
        """
        import logging

        known_models = {"mistral", "deepseek-coder", "openai"}
        if v not in known_models:
            logging.getLogger(__name__).warning(
                f"Unknown embedding model '{v}'. Known models: {known_models}"
            )
        return v


class Chunk(BaseModel):
    """
    A chunk of text with metadata.

    This is the canonical chunk structure used throughout the ingestion pipeline.
    All chunking strategies must return chunks conforming to this schema.

    Attributes:
        text: The actual text content of the chunk
        metadata: Metadata about the chunk

    Example:
        >>> chunk = Chunk(
        ...     text="This is a chunk of content.",
        ...     metadata=ChunkMetadata(
        ...         chunk_id="0",
        ...         document_id="doc123",
        ...         source="/path/to/file.py",
        ...         file_type="python",
        ...         chunk_index=0,
        ...         char_count=27,
        ...         embedding_model_id="deepseek-coder",
        ...         target_collection="scareverse_code"
        ...     )
        ... )
    """

    model_config = {
        "str_strip_whitespace": False,  # Preserve whitespace in text content
        "validate_assignment": True,  # Validate on assignment
    }

    text: str = Field(
        ..., description="The actual text content of the chunk", min_length=1
    )
    metadata: ChunkMetadata = Field(..., description="Metadata about the chunk")

    @model_validator(mode="after")
    def validate_char_count(self) -> "Chunk":
        """
        Validate that char_count matches actual text length if provided.
        Auto-populate char_count if not provided.

        Logs a warning if char_count doesn't match actual length.
        """
        import logging

        actual_length = len(self.text)

        if self.metadata.char_count is None:
            # Auto-populate char_count
            self.metadata.char_count = actual_length
        elif self.metadata.char_count != actual_length:
            # Log warning - char_count might include formatting that was stripped
            logging.getLogger(__name__).warning(
                f"char_count ({self.metadata.char_count}) doesn't match "
                f"actual text length ({actual_length}) for chunk {self.metadata.chunk_id}"
            )

        return self

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert chunk to dictionary format.

        Returns dictionary compatible with existing JSON serialization.
        """
        return {"text": self.text, "metadata": self.metadata.model_dump()}

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Chunk":
        """
        Create chunk from dictionary format.

        Args:
            data: Dictionary with 'text' and 'metadata' keys

        Returns:
            Validated Chunk instance

        Raises:
            ValidationError: If data doesn't conform to schema
        """
        return cls(**data)
