#!/bin/sh
#
# Cloudflared service entrypoint.
#
# Docker requirement: PID 1 must stay alive for the container to keep running.
# Strategy: heartbeat.py becomes PID 1 (runs in foreground, indefinitely).
#          cloudflared tunnel runs in background (if TUNNEL_TOKEN set).
#
# If either process dies, container exits (graceful failure detection).
#

set -e

echo "[entrypoint] Starting cloudflared service..."

# ============================================================================
# Generate config.yml from INGRESS_RULES if provided
# ============================================================================
# INGRESS_RULES is a JSON array generated by ServiceOrchestrator
# Example: [{"hostname": "scare.scareverse.net", "service": "http://nginx-unity:80"}, {"service": "http_status:404"}]

if [ -n "${INGRESS_RULES}" ]; then
  echo "[entrypoint] Generating config.yml from INGRESS_RULES..."
  cat > /app/config.yml <<EOF
# Generated by entrypoint.sh from INGRESS_RULES environment variable
tunnel: placeholder
ingress:
EOF

  # Parse INGRESS_RULES JSON and convert to YAML ingress rules
  # This uses Python to parse JSON and convert to YAML format
  python3 - "$INGRESS_RULES" <<'PYEOF' >> /app/config.yml
import sys
import json

try:
    rules = json.loads(sys.argv[1])
    for rule in rules:
        if 'hostname' in rule:
            print(f"  - hostname: {rule['hostname']}")
            print(f"    service: {rule['service']}")
        elif 'service' in rule:
            print(f"  - service: {rule['service']}")
except Exception as e:
    print(f"Error parsing INGRESS_RULES: {e}", file=sys.stderr)
    sys.exit(1)
PYEOF

  if [ $? -eq 0 ]; then
    echo "[entrypoint] ✅ Generated config.yml:"
    cat /app/config.yml
  else
    echo "[entrypoint] ❌ Failed to generate config.yml"
    exit 1
  fi
else
  echo "[entrypoint] ⚠️  INGRESS_RULES not set – tunnel will run without ingress configuration"
fi

# ============================================================================
# Start tunnel in background if TUNNEL_TOKEN is provided
# ============================================================================
# This runs as a background job. If it dies, heartbeat will continue.
# If heartbeat dies, container will exit (expected behavior).

if [ -n "${TUNNEL_TOKEN}" ]; then
  echo "[entrypoint] ✅ TUNNEL_TOKEN set – starting cloudflared tunnel in background..."
  if [ -f /app/config.yml ]; then
    cloudflared tunnel --no-autoupdate run --token "${TUNNEL_TOKEN}" --config /app/config.yml &
  else
    cloudflared tunnel --no-autoupdate run --token "${TUNNEL_TOKEN}" &
  fi
  TUNNEL_PID=$!
  echo "[entrypoint] Tunnel PID: $TUNNEL_PID"
else
  echo "[entrypoint] ⏸️  TUNNEL_TOKEN not set – running in heartbeat-only mode (bootstrap phase)"
fi

# ============================================================================
# Start heartbeat in FOREGROUND (as PID 1)
# ============================================================================
# exec replaces this shell process with heartbeat.py
# heartbeat.py becomes PID 1 and keeps the container alive indefinitely.
# When/if heartbeat.py exits, the container exits (graceful shutdown).

echo "[entrypoint] 🚀 Starting heartbeat in foreground (PID 1)..."
exec python /app/heartbeat.py
