"""
Cache Manager for L1 Redis caching of query results.

This module provides deterministic cache key generation using SHA256,
cache invalidation strategies with pattern matching, and TTL management
for query results in the Query Engine.

Architecture:
    CacheManager
    ├── generate_cache_key() - Deterministic SHA256-based key generation
    ├── get() - Retrieve from cache
    ├── set() - Store with TTL
    ├── set_with_index() - Store with secondary index for invalidation
    ├── invalidate() - Delete specific key
    ├── invalidate_for_collection() - Pattern-based collection invalidation
    └── get_cache_stats() - Cache statistics

Usage:
    from backend.app.database.query_engine.cache_manager import CacheManager
    from backend.app.core.redis_client import get_redis_client

    redis = await get_redis_client()
    cache = CacheManager(redis)

    # Generate cache key
    key = cache.generate_cache_key("templates", {"status": "published"}, "user1")

    # Store in cache
    await cache.set_with_index(key, results, "templates", "user1")

    # Retrieve from cache
    cached = await cache.get(key)

    # Invalidate all queries for a collection
    await cache.invalidate_for_collection("templates", "user1")
"""

import hashlib
import json
import logging
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


class CacheManager:
    """
    L1 Redis cache manager for query results.

    Provides deterministic cache key generation, TTL management,
    and pattern-based invalidation for query results.

    Attributes:
        redis: Async Redis client instance
        default_ttl: Default TTL in seconds (5 minutes)

    Example:
        cache = CacheManager(redis_client)

        # Cache a query result
        key = cache.generate_cache_key("templates", {"status": "active"}, "user1")
        await cache.set_with_index(key, results, "templates", "user1")

        # Retrieve cached result
        cached = await cache.get(key)

        # Invalidate all queries for a collection
        await cache.invalidate_for_collection("templates")
    """

    def __init__(self, redis_client):
        """
        Initialize Cache Manager with Redis client.

        Args:
            redis_client: Async Redis client instance
        """
        self.redis = redis_client
        self.default_ttl = 300  # 5 minutes

    def generate_cache_key(
        self, collection: str, query: Dict, user_id: str, limit: Optional[int] = None
    ) -> str:
        """
        Generate deterministic cache key using SHA256.

        Creates a deterministic hash-based cache key from query parameters.
        Same inputs always produce the same key, ensuring cache consistency.

        Args:
            collection: Collection name (e.g., "templates", "permissions")
            query: MongoDB-style query dict
            user_id: User ID (queries are user-specific for RBAC)
            limit: Optional limit parameter

        Returns:
            Cache key string in format "query:{sha256_hash}"

        Example:
            key = cache.generate_cache_key(
                "templates",
                {"status": "published", "owner": "user1"},
                "user1",
                limit=10
            )
            # Returns: "query:abc123def456..."
        """
        # Sort query dict for determinism
        query_str = json.dumps(query, sort_keys=True)

        # Build key components with explicit limit format
        # This avoids ambiguity between limit=None and limit=0
        components = [
            collection,
            query_str,
            user_id,
            f"limit:{limit}" if limit is not None else "limit:none",
        ]

        # Hash for compact key
        key_str = ":".join(components)
        hash_hex = hashlib.sha256(key_str.encode()).hexdigest()

        return f"query:{hash_hex}"

    async def get(self, key: str) -> Optional[List[Dict]]:
        """
        Retrieve query results from Redis cache.

        Args:
            key: Cache key generated by generate_cache_key()

        Returns:
            Cached query results (list of dicts) or None if cache miss

        Raises:
            Exception: If Redis operation fails

        Example:
            cached = await cache.get("query:abc123...")
            if cached:
                return cached  # Cache hit
            else:
                # Cache miss - query database
                pass
        """
        if self.redis is None:
            return None

        try:
            cached = await self.redis.get(key)
            if cached:
                return json.loads(cached)
            return None
        except Exception as e:
            logger.warning("Cache get failed for key %s: %s", key, e)
            return None

    async def set(self, key: str, value: List[Dict], ttl: Optional[int] = None):
        """
        Store query results in Redis cache with TTL.

        Args:
            key: Cache key
            value: Query results to cache (list of dicts)
            ttl: Time to live in seconds (default: 5 minutes)

        Raises:
            Exception: If Redis operation fails

        Example:
            await cache.set("query:abc123...", results, ttl=300)
        """
        if self.redis is None:
            return

        ttl = ttl or self.default_ttl

        try:
            # Serialize with default handler for datetime/etc
            value_json = json.dumps(value, default=str)

            await self.redis.setex(key, ttl, value_json)
        except Exception as e:
            logger.warning("Cache set failed for key %s: %s", key, e)

    async def invalidate(self, key: str):
        """
        Delete specific cache key.

        Args:
            key: Cache key to delete

        Example:
            await cache.invalidate("query:abc123...")
        """
        if self.redis is None:
            return

        try:
            await self.redis.delete(key)
        except Exception as e:
            logger.warning("Cache invalidate failed for key %s: %s", key, e)

    async def invalidate_for_collection(
        self, collection: str, user_id: Optional[str] = None
    ):
        """
        Invalidate all cached queries for a collection.

        Uses secondary index keys to find and delete all queries
        for a specific collection. Can be scoped to a specific user.

        Args:
            collection: Collection name (e.g., "templates", "permissions")
            user_id: Optional user ID to invalidate only that user's queries

        Example:
            # Invalidate all templates queries for user1
            await cache.invalidate_for_collection("templates", "user1")

            # Invalidate all templates queries for all users
            await cache.invalidate_for_collection("templates")
        """
        if self.redis is None:
            return

        try:
            # Pattern matching to find all queries for this collection
            if user_id:
                # More specific - only this user's queries for this collection
                pattern = f"query_index:{collection}:{user_id}:*"
            else:
                # All queries for this collection (all users)
                pattern = f"query_index:{collection}:*"

            cursor = 0
            while True:
                cursor, keys = await self.redis.scan(cursor, match=pattern, count=100)

                if keys:
                    # Get actual query keys from index
                    query_keys = []
                    for index_key in keys:
                        query_key = await self.redis.get(index_key)
                        if query_key:
                            query_keys.append(query_key)

                    # Delete query keys and index keys
                    if query_keys:
                        await self.redis.delete(*query_keys)
                    await self.redis.delete(*keys)

                if cursor == 0:
                    break

            logger.info("Invalidated cache for collection=%s, user_id=%s", collection, user_id)

        except Exception as e:
            logger.warning("Cache invalidation failed for collection %s: %s", collection, e)

    async def set_with_index(
        self,
        key: str,
        value: List[Dict],
        collection: str,
        user_id: str,
        ttl: Optional[int] = None,
    ):
        """
        Store query results in cache with indexing for efficient invalidation.

        Creates a secondary index key that maps collection+user to the query key,
        enabling efficient pattern-based invalidation when data changes.

        Index format: query_index:{collection}:{user_id}:{hash} -> query:{hash}

        Args:
            key: Cache key (from generate_cache_key)
            value: Query results to cache
            collection: Collection name
            user_id: User ID
            ttl: Time to live in seconds (default: 5 minutes)

        Example:
            key = cache.generate_cache_key("templates", query, "user1")
            await cache.set_with_index(key, results, "templates", "user1")

            # Later, invalidate all templates queries for user1
            await cache.invalidate_for_collection("templates", "user1")
        """
        # Store the actual query result
        await self.set(key, value, ttl)

        if self.redis is None:
            return

        try:
            # Create index for invalidation
            hash_part = key.split(":")[-1]
            index_key = f"query_index:{collection}:{user_id}:{hash_part}"

            ttl = ttl or self.default_ttl
            # Index TTL should be longer than query TTL to prevent orphaned indices
            # Add 1 hour buffer for async cleanup operations
            index_ttl = ttl + 3600
            await self.redis.setex(index_key, index_ttl, key)

        except Exception as e:
            logger.warning("Failed to create cache index for %s: %s", key, e)

    async def get_cache_stats(self) -> Dict:
        """
        Get cache statistics.

        Returns:
            Dictionary containing:
            - total_cached_queries: Total number of cached query results
            - default_ttl_seconds: Default TTL for cache entries

        Example:
            stats = await cache.get_cache_stats()
            print(f"Cached queries: {stats['total_cached_queries']}")
            print(f"Default TTL: {stats['default_ttl_seconds']}s")
        """
        if self.redis is None:
            return {"total_cached_queries": 0, "default_ttl_seconds": self.default_ttl}

        try:
            # Count query keys
            pattern = "query:*"
            cursor = 0
            total_keys = 0

            while True:
                cursor, keys = await self.redis.scan(cursor, match=pattern, count=1000)
                total_keys += len(keys)
                if cursor == 0:
                    break

            return {
                "total_cached_queries": total_keys,
                "default_ttl_seconds": self.default_ttl,
            }

        except Exception as e:
            logger.warning("Failed to get cache stats: %s", e)
            return {"total_cached_queries": 0, "default_ttl_seconds": self.default_ttl}
